### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by johmor52** [balmli/com.telldus.live#2]
When click on unit from teldus I get: api.onoffdevice is not a function.
Stopped working 3 day ago according to log.
I also have google home to manage units. Google can't operate.
I have version 7.2.0 in Homey Pro (early 2019).

What to do?

**Comment by balmli** [comment]
Try logging in to Telldus live.

Think the log in session lasts only 1 year

**Comment by johmor52** [comment]
In Homey app -> Apps -> Telldus Live. But where do I find the login screen?
In settings there is no Telldus Live.
I have had Telldus Live since v4.2.0 working.

**Comment by balmli** [comment]
Creating new tokens might help.

See top of this page: https://community.homey.app/t/app-pro-telldus-live/34779

**Comment by johmor52** [comment]
Thanks a Lot!
I now remember how I did a year ago.
I connected local as I did then. For some reason it hadn't renew as it said.
You where very helpful!
Regards Johan
